spring:
  application:
    name: aml-house-keeping

server:
  port: 8081

#management:
#    endpoints:
#        web:
#            exposure:
#                include: '*'
#spring:
#    application:
#        name: aml-house-keeping
#    config:
#        import: optional:configserver:http://localhost:8888/aml-centralize-configuration/
